FORMAT: 1A

# Spree API
WIP on JSON API for Spree.

# Products
Products related resources of the **Spree API**

## Products Collection [/products/{?q}]

### List all Products [GET]
+ Parameters
    + q (optional, string, `name_like="mug"`) ... Query string parameter to Ransack search

+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Product [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Product [/product/{id}]
A single Product object with all its details

+ Parameters
    + id (required, number, `5`) ... `id` of the Product to perform action with.

### Retrieve a Product [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }
